/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    OrderVault: {
      address: "0xc265045c65d0114109072d60b3a60231427a06a9",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "owner_",
              type: "address",
              internalType: "address",
            },
            {
              name: "router_",
              type: "address",
              internalType: "contract ISaucerSwapV2Router",
            },
            {
              name: "whbar_",
              type: "address",
              internalType: "address",
            },
            {
              name: "costs_",
              type: "tuple",
              internalType: "struct Costs",
              components: [
                {
                  name: "scheduleGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "sweepBaseGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "checkGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "fillGasHbarIn",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "fillGasTokenIn",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "settleGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "idleSweepGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "gasPriceTinycents",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "safetyBps",
                  type: "uint16",
                  internalType: "uint16",
                },
              ],
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "ROUTER",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISaucerSwapV2Router",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "WHBAR",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "acceptOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "cancel",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claim",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "collection",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "costs",
          inputs: [],
          outputs: [
            {
              name: "scheduleGas",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "sweepBaseGas",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "checkGas",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "fillGasHbarIn",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "fillGasTokenIn",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "settleGas",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "idleSweepGas",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "gasPriceTinycents",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "safetyBps",
              type: "uint16",
              internalType: "uint16",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "credits",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "escrowed",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "executeOrder",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "settled",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "fillFromVault",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "oraclePrice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "poolPrice",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "amountOut",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "fund",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "getMarket",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct Market",
              components: [
                {
                  name: "base",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "quote",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "baseDecimals",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "quoteDecimals",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "baseIsHbar",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "quoteIsHbar",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "baseFeed",
                  type: "address",
                  internalType: "contract IAggregatorV3",
                },
                {
                  name: "quoteFeed",
                  type: "address",
                  internalType: "contract IAggregatorV3",
                },
                {
                  name: "baseFeedDecimals",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "quoteFeedDecimals",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "pool",
                  type: "address",
                  internalType: "contract ISaucerSwapV2Pool",
                },
                {
                  name: "poolFee",
                  type: "uint24",
                  internalType: "uint24",
                },
                {
                  name: "baseIsToken0",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "active",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "guard",
                  type: "tuple",
                  internalType: "struct GuardParams",
                  components: [
                    {
                      name: "twapWindow",
                      type: "uint32",
                      internalType: "uint32",
                    },
                    {
                      name: "maxDeviationBps",
                      type: "uint16",
                      internalType: "uint16",
                    },
                    {
                      name: "maxOracleAge",
                      type: "uint32",
                      internalType: "uint32",
                    },
                    {
                      name: "maxSlippageBps",
                      type: "uint16",
                      internalType: "uint16",
                    },
                  ],
                },
                {
                  name: "sweep",
                  type: "tuple",
                  internalType: "struct SweepParams",
                  components: [
                    {
                      name: "minInterval",
                      type: "uint32",
                      internalType: "uint32",
                    },
                    {
                      name: "maxInterval",
                      type: "uint32",
                      internalType: "uint32",
                    },
                    {
                      name: "maxMoveBpsPerHour",
                      type: "uint16",
                      internalType: "uint16",
                    },
                    {
                      name: "maxOrders",
                      type: "uint16",
                      internalType: "uint16",
                    },
                    {
                      name: "maxFills",
                      type: "uint8",
                      internalType: "uint8",
                    },
                  ],
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getOrder",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct Order",
              components: [
                {
                  name: "marketId",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "side",
                  type: "uint8",
                  internalType: "enum Side",
                },
                {
                  name: "orderType",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum Status",
                },
                {
                  name: "funded",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "slippageBps",
                  type: "uint16",
                  internalType: "uint16",
                },
                {
                  name: "createdAt",
                  type: "uint40",
                  internalType: "uint40",
                },
                {
                  name: "expiry",
                  type: "uint40",
                  internalType: "uint40",
                },
                {
                  name: "amountIn",
                  type: "uint128",
                  internalType: "uint128",
                },
                {
                  name: "typeParam",
                  type: "uint128",
                  internalType: "uint128",
                },
                {
                  name: "budget",
                  type: "uint128",
                  internalType: "uint128",
                },
                {
                  name: "typeState",
                  type: "bytes32",
                  internalType: "bytes32",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "guardReading",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct GuardReading",
              components: [
                {
                  name: "state",
                  type: "uint8",
                  internalType: "enum GuardState",
                },
                {
                  name: "oraclePrice",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "poolPrice",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "deviationBps",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "oracleUpdatedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "holderOf",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "initialize",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "listMarket",
          inputs: [
            {
              name: "market",
              type: "tuple",
              internalType: "struct Market",
              components: [
                {
                  name: "base",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "quote",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "baseDecimals",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "quoteDecimals",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "baseIsHbar",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "quoteIsHbar",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "baseFeed",
                  type: "address",
                  internalType: "contract IAggregatorV3",
                },
                {
                  name: "quoteFeed",
                  type: "address",
                  internalType: "contract IAggregatorV3",
                },
                {
                  name: "baseFeedDecimals",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "quoteFeedDecimals",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "pool",
                  type: "address",
                  internalType: "contract ISaucerSwapV2Pool",
                },
                {
                  name: "poolFee",
                  type: "uint24",
                  internalType: "uint24",
                },
                {
                  name: "baseIsToken0",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "active",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "guard",
                  type: "tuple",
                  internalType: "struct GuardParams",
                  components: [
                    {
                      name: "twapWindow",
                      type: "uint32",
                      internalType: "uint32",
                    },
                    {
                      name: "maxDeviationBps",
                      type: "uint16",
                      internalType: "uint16",
                    },
                    {
                      name: "maxOracleAge",
                      type: "uint32",
                      internalType: "uint32",
                    },
                    {
                      name: "maxSlippageBps",
                      type: "uint16",
                      internalType: "uint16",
                    },
                  ],
                },
                {
                  name: "sweep",
                  type: "tuple",
                  internalType: "struct SweepParams",
                  components: [
                    {
                      name: "minInterval",
                      type: "uint32",
                      internalType: "uint32",
                    },
                    {
                      name: "maxInterval",
                      type: "uint32",
                      internalType: "uint32",
                    },
                    {
                      name: "maxMoveBpsPerHour",
                      type: "uint16",
                      internalType: "uint16",
                    },
                    {
                      name: "maxOrders",
                      type: "uint16",
                      internalType: "uint16",
                    },
                    {
                      name: "maxFills",
                      type: "uint8",
                      internalType: "uint8",
                    },
                  ],
                },
              ],
            },
          ],
          outputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "marketCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "openOrders",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "orderTypeActive",
          inputs: [
            {
              name: "id",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "orderTypeCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "orderTypes",
          inputs: [
            {
              name: "id",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [
            {
              name: "impl",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pendingOwner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "placeOrder",
          inputs: [
            {
              name: "p",
              type: "tuple",
              internalType: "struct PlaceParams",
              components: [
                {
                  name: "marketId",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "side",
                  type: "uint8",
                  internalType: "enum Side",
                },
                {
                  name: "orderType",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "amountIn",
                  type: "uint128",
                  internalType: "uint128",
                },
                {
                  name: "typeParam",
                  type: "uint128",
                  internalType: "uint128",
                },
                {
                  name: "slippageBps",
                  type: "uint16",
                  internalType: "uint16",
                },
                {
                  name: "expiry",
                  type: "uint40",
                  internalType: "uint40",
                },
              ],
            },
          ],
          outputs: [
            {
              name: "orderId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "registerOrderType",
          inputs: [
            {
              name: "impl",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "restartSweep",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setCosts",
          inputs: [
            {
              name: "costs_",
              type: "tuple",
              internalType: "struct Costs",
              components: [
                {
                  name: "scheduleGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "sweepBaseGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "checkGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "fillGasHbarIn",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "fillGasTokenIn",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "settleGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "idleSweepGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "gasPriceTinycents",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "safetyBps",
                  type: "uint16",
                  internalType: "uint16",
                },
              ],
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setOrderTypeActive",
          inputs: [
            {
              name: "id",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "sweep",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "epoch",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "sweeps",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "pendingSchedule",
              type: "address",
              internalType: "address",
            },
            {
              name: "nextSweepAt",
              type: "uint40",
              internalType: "uint40",
            },
            {
              name: "cursor",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "fundedOrders",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "epoch",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "heldStreak",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "topUp",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "totalBudgets",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalCredits",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "updateMarket",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "guard",
              type: "tuple",
              internalType: "struct GuardParams",
              components: [
                {
                  name: "twapWindow",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "maxDeviationBps",
                  type: "uint16",
                  internalType: "uint16",
                },
                {
                  name: "maxOracleAge",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "maxSlippageBps",
                  type: "uint16",
                  internalType: "uint16",
                },
              ],
            },
            {
              name: "sweepParams",
              type: "tuple",
              internalType: "struct SweepParams",
              components: [
                {
                  name: "minInterval",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "maxInterval",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "maxMoveBpsPerHour",
                  type: "uint16",
                  internalType: "uint16",
                },
                {
                  name: "maxOrders",
                  type: "uint16",
                  internalType: "uint16",
                },
                {
                  name: "maxFills",
                  type: "uint8",
                  internalType: "uint8",
                },
              ],
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawSurplus",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address payable",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "BudgetExhausted",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "budgetLeft",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "BudgetToppedUp",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "budget",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Claimed",
          inputs: [
            {
              name: "account",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "CollectionCreated",
          inputs: [
            {
              name: "collection",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "CostsUpdated",
          inputs: [
            {
              name: "costs",
              type: "tuple",
              indexed: false,
              internalType: "struct Costs",
              components: [
                {
                  name: "scheduleGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "sweepBaseGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "checkGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "fillGasHbarIn",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "fillGasTokenIn",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "settleGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "idleSweepGas",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "gasPriceTinycents",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "safetyBps",
                  type: "uint16",
                  internalType: "uint16",
                },
              ],
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Credited",
          inputs: [
            {
              name: "account",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "FillFailed",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "reason",
              type: "bytes",
              indexed: false,
              internalType: "bytes",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "FillHeld",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "reason",
              type: "uint8",
              indexed: false,
              internalType: "enum GuardState",
            },
            {
              name: "oraclePrice",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "poolPrice",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Funded",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MarketListed",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "base",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "quote",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "pool",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "poolFee",
              type: "uint24",
              indexed: false,
              internalType: "uint24",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MarketUpdated",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "NftSettlementFailed",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "responseCode",
              type: "int64",
              indexed: false,
              internalType: "int64",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OrderCancelled",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "holder",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "refund",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "budgetRefund",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OrderChecked",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "charged",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "budgetLeft",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OrderEvalSkipped",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OrderExpired",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "holder",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "refund",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "budgetRefund",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OrderFilled",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "holder",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amountIn",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "amountOut",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "minAmountOut",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "oraclePrice",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "poolPrice",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "budgetRefund",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OrderPlaced",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "marketId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "maker",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "side",
              type: "uint8",
              indexed: false,
              internalType: "enum Side",
            },
            {
              name: "orderType",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
            {
              name: "amountIn",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "typeParam",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "slippageBps",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "expiry",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "budget",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OrderStateUpdated",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "state",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OrderTypeActiveSet",
          inputs: [
            {
              name: "id",
              type: "uint8",
              indexed: true,
              internalType: "uint8",
            },
            {
              name: "active",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OrderTypeRegistered",
          inputs: [
            {
              name: "id",
              type: "uint8",
              indexed: true,
              internalType: "uint8",
            },
            {
              name: "impl",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferStarted",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SurplusWithdrawn",
          inputs: [
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SweepBroughtForward",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "charged",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "budgetLeft",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SweepExecuted",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "scheduled",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "guard",
              type: "uint8",
              indexed: false,
              internalType: "enum GuardState",
            },
            {
              name: "checked",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "filled",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "openOrders",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SweepScheduleFailed",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "responseCode",
              type: "int64",
              indexed: false,
              internalType: "int64",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SweepScheduled",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "schedule",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "executeAt",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "epoch",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SweepSuperseded",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "epoch",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyInitialized",
          inputs: [],
        },
        {
          type: "error",
          name: "HtsError",
          inputs: [
            {
              name: "operation",
              type: "uint8",
              internalType: "enum HtsOperation",
            },
            {
              name: "responseCode",
              type: "int64",
              internalType: "int64",
            },
          ],
        },
        {
          type: "error",
          name: "InsufficientBudget",
          inputs: [
            {
              name: "provided",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "required",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "InvalidAmount",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidCosts",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidExpiry",
          inputs: [
            {
              name: "expiry",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "InvalidGuard",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidMarket",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidOrderParams",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidSlippage",
          inputs: [
            {
              name: "slippageBps",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "minBps",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxBps",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "InvalidSweep",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidTrigger",
          inputs: [],
        },
        {
          type: "error",
          name: "MarketInactive",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "NoFundedOrders",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "NotHolder",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "caller",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "NotInitialized",
          inputs: [],
        },
        {
          type: "error",
          name: "NotRouter",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "NothingToClaim",
          inputs: [],
        },
        {
          type: "error",
          name: "OnlySelf",
          inputs: [],
        },
        {
          type: "error",
          name: "OrderNotOpen",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "OrderTypeInactive",
          inputs: [
            {
              name: "id",
              type: "uint8",
              internalType: "uint8",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeCastOverflowedUintDowncast",
          inputs: [
            {
              name: "bits",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "SweepAlive",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "nextSweepAt",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "TransferFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "UnknownMarket",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "UnknownOrderType",
          inputs: [
            {
              name: "id",
              type: "uint8",
              internalType: "uint8",
            },
          ],
        },
        {
          type: "error",
          name: "WrongValue",
          inputs: [
            {
              name: "sent",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "expected",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41223029,
    },
    LimitOrderType: {
      address: "0x0b6dedd3fdf794be447efc4da514207259977cca",
      abi: [
        {
          type: "function",
          name: "evaluate",
          inputs: [
            {
              name: "side",
              type: "uint8",
              internalType: "enum Side",
            },
            {
              name: "param",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "state",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "oraclePrice",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "distanceBps",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "newState",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "minOut",
          inputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum Side",
            },
            {
              name: "",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "validate",
          inputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum Side",
            },
            {
              name: "amountIn",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "param",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
            {
              name: "",
              type: "uint40",
              internalType: "uint40",
            },
            {
              name: "",
              type: "uint40",
              internalType: "uint40",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "pure",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41223042,
    },
    StopOrderType: {
      address: "0x11dfda5ca30d3ed806d24ec0cc8eee06b0872c2b",
      abi: [
        {
          type: "function",
          name: "evaluate",
          inputs: [
            {
              name: "side",
              type: "uint8",
              internalType: "enum Side",
            },
            {
              name: "param",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "state",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "oraclePrice",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "distanceBps",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "newState",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "minOut",
          inputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum Side",
            },
            {
              name: "",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "validate",
          inputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum Side",
            },
            {
              name: "amountIn",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "param",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
            {
              name: "",
              type: "uint40",
              internalType: "uint40",
            },
            {
              name: "",
              type: "uint40",
              internalType: "uint40",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "pure",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41223046,
    },
    TrailingStopType: {
      address: "0x2e449f0ed73d54239b9cd647d0a23ab1d9c78a36",
      abi: [
        {
          type: "function",
          name: "MAX_TRAIL_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint128",
              internalType: "uint128",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_TRAIL_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint128",
              internalType: "uint128",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "evaluate",
          inputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum Side",
            },
            {
              name: "param",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "state",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "oraclePrice",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "distanceBps",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "newState",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "minOut",
          inputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum Side",
            },
            {
              name: "",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "validate",
          inputs: [
            {
              name: "side",
              type: "uint8",
              internalType: "enum Side",
            },
            {
              name: "amountIn",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "param",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "",
              type: "uint16",
              internalType: "uint16",
            },
            {
              name: "",
              type: "uint40",
              internalType: "uint40",
            },
            {
              name: "",
              type: "uint40",
              internalType: "uint40",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "pure",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41223053,
    },
    OrderVaultLens: {
      address: "0x71bef6696d1c684f2f9d1581f4adb07e9d7e9d8e",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "vault_",
              type: "address",
              internalType: "contract OrderVault",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "VAULT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract OrderVault",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "checkCost",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "checkCostShared",
          inputs: [
            {
              name: "fundedOrders",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "fillCost",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "side",
              type: "uint8",
              internalType: "enum Side",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "minBudget",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "side",
              type: "uint8",
              internalType: "enum Side",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextBatch",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "batch",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextCheckDelay",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "orderType",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "side",
              type: "uint8",
              internalType: "enum Side",
            },
            {
              name: "typeParam",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "expiry",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "orderNextCheckDelay",
          inputs: [
            {
              name: "orderId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "payerFloat",
          inputs: [],
          outputs: [
            {
              name: "float",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "previewCharges",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "share",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "parkFee",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "surplus",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sweepGasLimit",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sweepStatus",
          inputs: [
            {
              name: "marketId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "status",
              type: "uint8",
              internalType: "enum SweepStatus",
            },
            {
              name: "nextSweepAt",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "error",
          name: "InvalidCosts",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41223060,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
